# rename col descriptions to shorter and usable variable names
require(dplyr)
df_srl_na_col <- rename(
  df_srl_na,
  PD_00_ID = "ID",
  PD_01_age = "In welcher Altersgruppe befindest du dich?",
  PD_02_gender = "Welchem Geschlecht fühlst du dich zugehörig?",
  PD_03_employer = "In welchem Teil der DSVGruppe arbeitest du derzeit?",
  PD_04_work_yrs = "Wie viele Jahre bist du bereits bei deinem jetzigen Arbeitgeber innerhalb der DSVGruppe tätig?",
  PD_05_work_hrs = "Welche Erwerbssituation trifft auf dich zu?",
  PD_06_leader = "Bist du in einer fachlichen oder disziplinarischen Führungsposition?",
  PD_07_ho_amount = "Wie viel Prozent des Monats arbeitest du normalerweise von zu Hause aus?",
  WLA_08_info_acquire = "Neue Informationen beschaffen (z. B. durch Suche im Internet oder in der Wissensdatenbank des Unternehmens)",
  WLA_09_collab_solution = "Allein oder mit anderen zusammenarbeiten, um Lösungen für Probleme zu entwickeln",
  WLA_10_collab_ideas = "Allein oder mit anderen zusammen neue Ideen entwickeln",
  WLA_11_dev_field = "Neue Entwicklungen in deinem Fachgebiet verfolgen",
  WLA_12_new_tasks = "Neue Aufgaben ausführen",
  WLA_13_advice = "Kollegen um Rat fragen",
  WLA_14_self_study = "An einen Schulungskurs teilnehmen oder Materialien zum Selbststudium verwenden",
  WLA_15_copy_strategies = "Strategien von Kollegen beobachten oder kopieren, um eine Aufgabe zu erledigen oder ein Problem zu lösen",
  WLA_16_trial_error = "Durch Versuch und Irrtum einen besseren Weg finden, eine Aufgabe auszuführen",
  WLA_17_reflection = "Über früheres Handeln reflektieren",
  WLA_18_feedback = "Feedback von Kollegen zu deinen Aufgaben bekommen",
  SRL_F_19_personal_standards = "Ich setze persönliche Maßstäbe für die Leistung in meinem Job",
  SRL_F_20_long_term_goals = "Ich setze mir langfristige Ziele (monatlich oder jährlich), um meine Lernaktivitäten zu steuern",
  SRL_F_21_goals_time_learn = "Ich setze mir Ziele, die mir helfen, die Zeit, die ich mit Lernen verbringe, zu verwalten",
  SRL_F_22_deadlines = "Ich setze mir realistische Fristen für das Lernen, wenn ich einen Lernbedarf festgestellt habe.",
  SRL_F_23_question_self = "Ich stelle mir Fragen zu jeder Lernaufgabe, bevor ich beginne",
  SRL_F_24_dif_ways_solve = "Ich überlege mir mehrere Möglichkeiten zur Lösung eines Problems und wähle die beste aus",
  SRL_F_25_past_strategies = "Bei der Planung meines Lernens wende ich Strategien an, die sich in der Vergangenheit bewährt haben",
  SRL_F_26_spec_strategies = "Ich verwende spezifische Strategien für verschiedene Arten von Dingen, die ich lernen muss",
  SRL_F_27_apply_learned = "Ich denke, dass ich das, was ich in diesem Beruf lerne, in der Zukunft anwenden kann",
  SRL_F_28_learn_new = "Es ist wichtig für mich, in diesem Job neue Dinge zu lernen",
  SRL_F_29_learning_important = "Die Lernaktivitäten, die ich in diesem Job betreibe, sind wichtig für mich",
  SRL_F_30_difficulties_calm = "Ich kann bei Schwierigkeiten in meinem Job ruhig bleiben, weil ich mich auf meine Fähigkeiten verlassen kann.",
  SRL_F_31_problem_solutions = "Wenn ich in meinem Job mit einem Problem konfrontiert bin, kann ich normalerweise mehrere Lösungen dafür finden.",
  SRL_F_32_handle_whatever = "Was auch immer in meinem Job auf mich zukommt, ich kann es normalerweise bewältigen.",
  SRL_F_33_job_exp_future = "Meine bisherigen Erfahrungen in meinem Job haben mich gut auf meine berufliche Zukunft vorbereitet.",
  SRL_F_34_self_goals_set = "Ich erreiche die Ziele, die ich mir in meinem Job gesetzt habe.",
  SRL_F_35_job_demands = "Ich fühle mich auf die meisten Anforderungen in meinem Job vorbereitet.",
  SRL_P_36_plan_learning_goals = "Ich schreibe einen Plan, um zu beschreiben, wie ich meine Lernziele zu erreichen hoffe",
  SRL_P_37_rel_learn_now_past = "Ich hinterfrage, wie das, was ich gerade lerne, mit dem zusammenhängt, was ich bereits weiß.",
  SRL_P_38_change_strategies = "Ich ändere meine Strategien, wenn ich beim Lernen keine Fortschritte mache",
  SRL_P_39_make_notes = "Beim Lernen mache ich mir Notizen (einschließlich Diagramme usw), die mir helfen, meine Gedanken zu ordnen",
  SRL_P_40_meaning_signif_info = "Ich konzentriere mich auf den Sinn und die Bedeutung neuer Informationen",
  SRL_P_41_organize_time = "Ich organisiere meine Zeit so, dass ich meine Ziele bestmöglich erreiche",
  SRL_P_42_rel_knowl_now_past = "Wenn ich lerne, versuche ich, neues Wissen mit dem zu verknüpfen, was ich bereits weiß",
  SRL_P_43_collect_info = "Beim Lernen trage ich Informationen aus verschiedenen Quellen zusammen (zB: Personen und Ressourcen)",
  SRL_P_44_ideas_prev_exp = "Ich versuche, Ideen aus meiner früheren Erfahrung auf meine Arbeit anzuwenden, wo es angebracht ist",
  SRL_P_45_resources_start_pt = "Beim Lernen betrachte ich die Ressourcen, die ich finde, als Ausgangspunkt und versuche, daraus meine eigenen Ideen zu entwickeln",
  SRL_P_46_play_ideas = "Ich versuche, mit eigenen Ideen in Bezug auf das, was ich lerne, zu spielen",
  SRL_P_47_alt_ways_tasks = "Bei meiner Arbeit denke ich über alternative Wege nach, meine Aufgaben auszuführen",
  SRL_P_48_ask_help_colleagues = "Wenn ich eine Aufgabe nicht verstehe, bitte ich meine Kollegen um Hilfe.",
  SRL_P_49_identify_colleagues = "Ich versuche, an meinem Arbeitsplatz Kollegen zu identifizieren, die ich um Hilfe bitten kann, wenn ich sie brauche",
  SRL_P_50_lookup_unsure = "Wenn ich mir über etwas unsicher bin, schlage ich es nach",
  SRL_P_51_knowl_gaps = "Ich fülle meine Wissenslücken auf, indem ich mir dazu passendes Informationsmaterial besorge",
  SRL_P_52_challenge_job = "Wenn ich bei meiner Arbeit vor einer Herausforderung stehe, versuche ich, das Problem so eingehend wie möglich zu verstehen",
  SRL_P_53_opportunities_learn = "Ich mag Gelegenheiten, mich mit Aufgaben zu beschäftigen, bei denen ich lernen muss",
  SRL_P_54_taks_curiosity = "Ich bevorzuge Aufgaben, die meine Neugierde wecken, auch wenn ich Neues lernen muss, um diese zu erfüllen",
  SRL_SR_55_task_done_well_learned = "Ich weiß, wie gut ich gelernt habe, wenn ich eine Aufgabe erledigt habe",
  SRL_SR_56_dif_ways_task_done = "Ich frage mich, ob es andere Wege gegeben hätte, eine bereits erledigte Aufgabe zu vollenden.",
  SRL_SR_57_things_learned_finish = "Ich denke nach dem Lernen darüber nach, was ich gelernt habe.",
  SRL_SR_58_big_picture = 'Ich denke darüber nach, wie das, was ich gelernt habe, in das "Gesamtbild" meines Unternehmens passt',
  SRL_SR_59_things_learned_team = "Ich überlege, wie sich das, was ich gelernt habe, auf mein Team bezieht",
  SRL_SR_60_new_info_impact = "Ich versuche zu verstehen, wie sich neue Informationen, die ich gelernt habe, auf meine Arbeit auswirken",
  WLC_61_job_creative = "Mein Job verlangt von mir, kreativ zu sein",
  WLC_62 = "Ich kann mir meine Arbeitsaufgaben aussuchen",
  WLC_63_spec_abilities = "Ich habe die Möglichkeit, meine eigenen besonderen Fähigkeiten zu entwickeln",
  WLC_64_vary_ways_work = "Ich kann variieren, auf welche Art und Weise ich meine Arbeit erledige",
  WLC_65_high_degr_competency = "Mein Job erfordert ein hohes Maß an Kompetenz",
  WLC_66_learn_new_things = "Meine Job erfordert, dass ich neue Dinge lerne",
  SE_67_goals_assigned = "Wenn ich von zuhause aus arbeite, erreiche ich die Ziele, die mir gesetzt werden",
  SE_68_schedules_deadlines = "Wenn ich von zuhause aus arbeite, halte ich Zeitpläne und Arbeitsfristen ein",
  SE_69_new_work_methods = "Wenn ich von zuhause aus arbeite, erlerne ich neue Arbeitsmethoden",
  SE_70_work_all_energy = "Wenn ich von zuhause aus arbeite, setze ich meine ganze Energie für die Arbeit ein",
  SE_71_finish_all_work = "Wenn ich von zuhause aus arbeite, erledige ich alle zugewiesenen Aufgaben",
  SE_72_collab_home = "Wenn ich von zuhause aus arbeite, arbeite ich mit anderen Kollegen zusammen",
  SE_73_good_rel = "Wenn ich von zuhause aus arbeite, habe ich gute Beziehungen zu meinen direkten Vorgesetzten",
  SE_74_diverse_people = "Wenn ich von zuhause aus arbeite, arbeite ich mit Menschen unterschiedlicher Erfahrung und unterschiedlichen Alters zusammen",
  SE_75_work_team_easy = "Wenn ich von zuhause aus arbeite, kann ich problemlos in einem Team arbeiten",
)



View(df_srl_na_col)
