# rename col descriptions to shorter and usable variable names
df_srl_na_col <- rename(
  df_srl_na,
  PD_01 = 'In welcher Altersgruppe befindest du dich?',
  PD_02 = 'Welchem Geschlecht fühlst du dich zugehörig?',
  PD_03 = 'In welchem Teil der DSVGruppe arbeitest du derzeit?',
  PD_04 = 'Wie viele Jahre bist du bereits bei deinem jetzigen Arbeitgeber innerhalb der DSVGruppe tätig?',
  PD_05 = 'Welche Erwerbssituation trifft auf dich zu?',
  PD_06 = 'Bist du in einer fachlichen oder disziplinarischen Führungsposition?',
  PD_07 = 'Wie viel Prozent des Monats arbeitest du normalerweise von zu Hause aus?',
  WLA_08 = 'Neue Informationen beschaffen (z. B. durch Suche im Internet oder in der Wissensdatenbank des Unternehmens)',
  WLA_09 = 'Allein oder mit anderen zusammenarbeiten, um Lösungen für Probleme zu entwickeln',
  WLA_10 = 'Allein oder mit anderen zusammen neue Ideen entwickeln',
  WLA_11 = 'Neue Entwicklungen in deinem Fachgebiet verfolgen',
  WLA_12 = 'Neue Aufgaben ausführen',
  WLA_13 = 'Kollegen um Rat fragen',
  WLA_14 = 'An einen Schulungskurs teilnehmen oder Materialien zum Selbststudium verwenden',
  WLA_15 = 'Strategien von Kollegen beobachten oder kopieren, um eine Aufgabe zu erledigen oder ein Problem zu lösen',
  WLA_16 = 'Durch Versuch und Irrtum einen besseren Weg finden, eine Aufgabe auszuführen',
  WLA_17 = 'Über früheres Handeln reflektieren',
  WLA_18 = 'Feedback von Kollegen zu deinen Aufgaben bekommen',
  SRL_F_19 = 'Ich setze persönliche Maßstäbe für die Leistung in meinem Job',
  SRL_F_20 = 'Ich setze mir langfristige Ziele (monatlich oder jährlich), um meine Lernaktivitäten zu steuern',
  SRL_F_21 = 'Ich setze mir Ziele, die mir helfen, die Zeit, die ich mit Lernen verbringe, zu verwalten',
  SRL_F_22 = 'Ich setze mir realistische Fristen für das Lernen, wenn ich einen Lernbedarf festgestellt habe.',
  SRL_F_23 = 'Ich stelle mir Fragen zu jeder Lernaufgabe, bevor ich beginne',
  SRL_F_24 = 'Ich überlege mir mehrere Möglichkeiten zur Lösung eines Problems und wähle die beste aus',
  SRL_F_25 = 'Bei der Planung meines Lernens wende ich Strategien an, die sich in der Vergangenheit bewährt haben',
  SRL_F_26 = 'Ich verwende spezifische Strategien für verschiedene Arten von Dingen, die ich lernen muss',
  SRL_F_27 = 'Ich denke, dass ich das, was ich in diesem Beruf lerne, in der Zukunft anwenden kann',
  SRL_F_28 = 'Es ist wichtig für mich, in diesem Job neue Dinge zu lernen',
  SRL_F_29 = 'Die Lernaktivitäten, die ich in diesem Job betreibe, sind wichtig für mich',
  SRL_F_30 = 'Ich kann bei Schwierigkeiten in meinem Job ruhig bleiben, weil ich mich auf meine Fähigkeiten verlassen kann.',
  SRL_F_31 = 'Wenn ich in meinem Job mit einem Problem konfrontiert bin, kann ich normalerweise mehrere Lösungen dafür finden.',
  SRL_F_32 = 'Was auch immer in meinem Job auf mich zukommt, ich kann es normalerweise bewältigen.',
  SRL_F_33 = 'Meine bisherigen Erfahrungen in meinem Job haben mich gut auf meine berufliche Zukunft vorbereitet.',
  SRL_F_34 = 'Ich erreiche die Ziele, die ich mir in meinem Job gesetzt habe.',
  SRL_F_35 = 'Ich fühle mich auf die meisten Anforderungen in meinem Job vorbereitet.',
  SRL_P_36 = 'Ich schreibe einen Plan, um zu beschreiben, wie ich meine Lernziele zu erreichen hoffe',
  SRL_P_37 = 'Ich hinterfrage, wie das, was ich gerade lerne, mit dem zusammenhängt, was ich bereits weiß.',
  SRL_P_38 = 'Ich ändere meine Strategien, wenn ich beim Lernen keine Fortschritte mache',
  SRL_P_39 = 'Beim Lernen mache ich mir Notizen (einschließlich Diagramme usw), die mir helfen, meine Gedanken zu ordnen',
  SRL_P_40 = 'Ich konzentriere mich auf den Sinn und die Bedeutung neuer Informationen',
  SRL_P_41 = 'Ich organisiere meine Zeit so, dass ich meine Ziele bestmöglich erreiche',
  SRL_P_42 = 'Wenn ich lerne, versuche ich, neues Wissen mit dem zu verknüpfen, was ich bereits weiß',
  SRL_P_43 = 'Beim Lernen trage ich Informationen aus verschiedenen Quellen zusammen (zB: Personen und Ressourcen)',
  SRL_P_44 = 'Ich versuche, Ideen aus meiner früheren Erfahrung auf meine Arbeit anzuwenden, wo es angebracht ist',
  SRL_P_45 = 'Beim Lernen betrachte ich die Ressourcen, die ich finde, als Ausgangspunkt und versuche, daraus meine eigenen Ideen zu entwickeln',
  SRL_P_46 = 'Ich versuche, mit eigenen Ideen in Bezug auf das, was ich lerne, zu spielen',
  SRL_P_47 = 'Bei meiner Arbeit denke ich über alternative Wege nach, meine Aufgaben auszuführen',
  SRL_P_48 = 'Wenn ich eine Aufgabe nicht verstehe, bitte ich meine Kollegen um Hilfe.',
  SRL_P_49 = 'Ich versuche, an meinem Arbeitsplatz Kollegen zu identifizieren, die ich um Hilfe bitten kann, wenn ich sie brauche',
  SRL_P_50 = 'Wenn ich mir über etwas unsicher bin, schlage ich es nach',
  SRL_P_51 = 'Ich fülle meine Wissenslücken auf, indem ich mir dazu passendes Informationsmaterial besorge',
  SRL_P_52 = 'Wenn ich bei meiner Arbeit vor einer Herausforderung stehe, versuche ich, das Problem so eingehend wie möglich zu verstehen',
  SRL_P_53 = 'Ich mag Gelegenheiten, mich mit Aufgaben zu beschäftigen, bei denen ich lernen muss',
  SRL_P_54 = 'Ich bevorzuge Aufgaben, die meine Neugierde wecken, auch wenn ich Neues lernen muss, um diese zu erfüllen',
  SRL_SR_55 = 'Ich weiß, wie gut ich gelernt habe, wenn ich eine Aufgabe erledigt habe',
  SRL_SR_56 = 'Ich frage mich, ob es andere Wege gegeben hätte, eine bereits erledigte Aufgabe zu vollenden.',
  SRL_SR_57 = 'Ich denke nach dem Lernen darüber nach, was ich gelernt habe.',
  SRL_SR_58 = 'Ich denke darüber nach, wie das, was ich gelernt habe, in das "Gesamtbild" meines Unternehmens passt',
  SRL_SR_59 = 'Ich überlege, wie sich das, was ich gelernt habe, auf mein Team bezieht',
  SRL_SR_60 = 'Ich versuche zu verstehen, wie sich neue Informationen, die ich gelernt habe, auf meine Arbeit auswirken',
  WLC_61 = 'Mein Job verlangt von mir, kreativ zu sein',
  WLC_62 = 'Ich kann mir meine Arbeitsaufgaben aussuchen',
  WLC_63 = 'Ich habe die Möglichkeit, meine eigenen besonderen Fähigkeiten zu entwickeln',
  WLC_64 = 'Ich kann variieren, auf welche Art und Weise ich meine Arbeit erledige',
  WLC_65 = 'Mein Job erfordert ein hohes Maß an Kompetenz',
  WLC_66 = 'Meine Job erfordert, dass ich neue Dinge lerne',
  SE_67 = 'Wenn ich von zuhause aus arbeite, erreiche ich die Ziele, die mir gesetzt werden',
  SE_68 = 'Wenn ich von zuhause aus arbeite, halte ich Zeitpläne und Arbeitsfristen ein',
  SE_69 = 'Wenn ich von zuhause aus arbeite, erlerne ich neue Arbeitsmethoden',
  SE_70 = 'Wenn ich von zuhause aus arbeite, setze ich meine ganze Energie für die Arbeit ein',
  SE_71 = 'Wenn ich von zuhause aus arbeite, erledige ich alle zugewiesenen Aufgaben',
  SE_72 = 'Wenn ich von zuhause aus arbeite, arbeite ich mit anderen Kollegen zusammen',
  SE_73 = 'Wenn ich von zuhause aus arbeite, habe ich gute Beziehungen zu meinen direkten Vorgesetzten',
  SE_74 = 'Wenn ich von zuhause aus arbeite, arbeite ich mit Menschen unterschiedlicher Erfahrung und unterschiedlichen Alters zusammen',
  SE_75 = 'Wenn ich von zuhause aus arbeite, kann ich problemlos in einem Team arbeiten',
)



View(df_srl_na_col)
